### ISSUE TITLE
Docker Runtime is always set to "runc" by iotedgehubdev

### ISSUE THREAD

**Issue by toolboc** [Azure/iotedgehubdev#205] opened 2019-08-08 20:24 UTC
I am developing a GPU accelerated IoT Edge module on an Nvidia Jetson Xavier device that requires setting the Docker runtime to "nvidia" to ensure that created modules are bootstrapped with [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) to allow appropriate access to the system GPU resources and CUDA librarires.

The module settings from my deployment.template.json can be seen below:

```
        "modules": {
          "DeepStreamModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "nvcr.io/nvidia/deepstream-l4t:4.0-19.07",
              "createOptions": {
                "HostConfig": {
                  "Runtime": "nvidia"
                },
                "WorkingDir": "/root/deepstream_sdk_v4.0_jetson/sources/apps/sample_apps/deepstream-test4",
                "Entrypoint": [
                  "/opt/nvidia/deepstream/deepstream-4.0/bin/deepstream-test4-app",
                  "-i",
                  "/root/deepstream_sdk_v4.0_jetson/samples/streams/sample_720p.h264",
                  "--proto-lib",
                  "/opt/nvidia/deepstream/deepstream-4.0/lib/libnvds_azure_edge_proto.so",
                  "--no-display",
                  "--schema",
                  "1",
                  "--topic",
                  "deepstream"
                ]
              }
            }
          }
```

These settings work perfectly fine in a deployment configuration and set the Docker Runtime appropriately:

```
docker inspect DeepStreamModule | grep Runtime
            "Runtime": "nvidia"
```

However, when the DeepStreamModule is created using the IoT Edge Simulator, I get the following result:

```
docker inspect DeepStreamModule | grep Runtime
            "Runtime": "runc",
```

Is it possible to override this behavior to allow setting of the Docker Runtime to something other than "runc"?

**Comment by adashen** [comment] 2019-08-09 01:02
@toolboc Thank you very much to report the issue! We will investigate it and keep you updated when it is fixed.

**Comment by SLdragon** [comment] 2019-08-13 01:44
Thanks for your feedback, we will try to add Runtime support in future relesase

**Comment by SLdragon** [comment] 2020-01-10 07:17
Hi, @toolboc , from our investigation, only docker-compose.yaml with version 2.3, 2.4 supported runtime config, and it is not supported by version 3.x.

https://github.com/docker/compose/issues/6239

So we will keep this issue open until docker-compose.yaml file 3.x supported this feature.

**Comment by konichi3** [comment] 2021-01-09 00:56
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:56 UTC
Labels: external dependency, feature request
