### ISSUE TITLE
[Windows container]  debug csharp module failed

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#62] opened 2018-08-01 09:29 UTC
repro on : 
windows10
docker * windows container
Csharp local module testing

test case : Start edgehub for local module testing (csharp) 
Run “Iotedgehubdev modulecred” 
Copy the output env to the csharp launch debug configuration in vscode 
Run “iotedgehubdev start -i <input name>” 
Make sure it is successfully started and “curl” message shows up 
In vscode F5 to start the debugger. 
verify the error in screenshot.

![image](https://user-images.githubusercontent.com/35018765/43513439-4de6e420-95b0-11e8-9528-3720577e22a1.png)
docker logs edgeHubDev
![image](https://user-images.githubusercontent.com/35018765/43513469-6633f306-95b0-11e8-956b-2caf814bf9f2.png)

**Comment by adashen** [comment] 2019-03-28 02:58
@czgtest  please check this issue again with the latest docker version

**Comment by czgtest** [comment] 2019-03-29 03:16
@adashen  this issue still repro on windows-container.  prot 53000 and 8883 are not finding by default.
user need to check "Experimental Features" in docker settings,  prot 53000 and 8883 are finding when send request ,but breakpoint is not hit

![image](https://user-images.githubusercontent.com/35018765/55207178-1c5a1500-5214-11e9-94a8-8551306d0149.png)

![image](https://user-images.githubusercontent.com/35018765/55207150-12381680-5214-11e9-9750-f47012deb544.png)

**Comment by czgtest** [comment] 2019-03-29 03:22
by the way,  local debug for c# module  work well on docker liunx container

**Comment by adashen** [comment] 2019-12-12 03:23
@czgtest please check the single module debug scenario for csharp module with windows container again. And close the issue if could not reproduce.

**Comment by czgtest** [comment] 2019-12-16 05:26
local debug csharp module with windows container , breakpoint is not hit. so keep it open

**Comment by adashen** [comment] 2019-12-16 06:38
switch to amqp it works. It should be the SDK issue on mqtt. https://github.com/Azure/azure-iot-sdk-csharp/issues/574

**Comment by alesomas** [comment] 2020-03-25 14:14
Hi, I'm not able to start iotedgehubdev having docker set with Windows containers (switching to Linux containers it works); I receive the following error trying to start it from cmd:

_Network azure-iot-edge-dev is external, skipping
ERROR: Could not start container: af67a255c6ea3474d53fc6092509ce68438d5d4d893aaa0e55d4a5dbd39f3066 : 500 Server Error: Internal Server Error ("failed to create endpoint edgeHubDev on network azure-iot-edge-dev: failed during hnsCallRawResponse: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20)")_

I've tried different workarounds found on other sites (https://github.com/docker/for-win/issues/3171), like excluding some port ranges from reservation performed by Hyper-V, but no way.

**Comment by konichi3** [comment] 2021-01-09 00:55
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:55 UTC
Labels: external dependency
