### ISSUE TITLE
Access is denied error when debug C# module on Mac

### ISSUE THREAD

**Issue by w12379564** [Azure/iotedgehubdev#30] opened 2018-07-12 06:26 UTC
```
Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Security.Cryptography.CryptographicException : Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Microsoft.Azure.Devices.Client.Edge.InstalledCertificateValidator.SetupCertificateValidation()
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.GetCertificateValidator(IList`1 certs)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.<CreateInternalClientFromEnvironmentAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SampleModule.Program.<Init>d__3.MoveNext() in /Users/yuxianggan/Documents/test/EdgeSolution/modules/SampleModule/Program.cs:line 51
```

**Comment by nelsonmorais** [comment] 2019-01-20 00:39
Using iotedgehubdev version 0.6.0 I have the same issue, even after adding the **edge-device-ca.cert.pem** to the keychain. I don't see any environment variable named **EdgeModuleCACertificateFile**.

So the workaround provided did not work on my case. Any other options?

**Comment by adashen** [comment] 2019-01-22 08:47
@nelsonmorais , The work around steps are used to local debug the CSharp module on mac. If you are using vscode iot edge extension in VSCode. The step could be the follows
1. Start IoT Edge Simulator for Single Module
2. in .vscode/launch.json, remove the env "EdgeModuleCACertificateFile" in your CSharp module project launch mode debug setting.
3. Add the edge-device-ca.cert.pem into your keychain.
4. Start debugging the csharp module in launch mode.

**Comment by nelsonmorais** [comment] 2019-01-23 16:03
That worked, thanks!
Can you share if this is an issue that will be addressed soon on a next release, or this is a workaround that will stay for a longer period?

**Comment by adashen** [comment] 2019-01-24 02:00
@nelsonmorais Great to know it works! It's a workaround may stay for longer period, since the fix could not happen in this tool instead it needs CSharp SDK to support it.

**Comment by nelsonmorais** [comment] 2019-01-24 15:02
Hi @adashen ,

Thanks for the info.

**Comment by eXXL** [comment] 2019-02-20 09:16
Hi there,
I ran into the same issue while trying the howto. Where do I find the edge-device-ca.cert.pem and how do I add it to the keychain?

**Comment by adashen** [comment] 2019-02-20 09:23
@eXXL you could run "iotedgehubdev modulecred" to show the CA location. it is output as the value of "EdgeModuleCACertificateFile". As for how to add the certificate into keychain, you may refer to this link https://www.sslsupportdesk.com/how-to-import-a-certificate-into-mac-os/

**Comment by eXXL** [comment] 2019-02-20 09:39
Hi @adashen,
this helped me out and it worked!

Thank you,
Alex

**Comment by czgtest** [comment] 2019-03-29 01:44
@adashen this issue still repro on mac when local debug C# module

**Comment by dmaxwe22** [comment] 2019-07-20 17:25
Thank you, @adashen, that worked for me. I searched for a solution for one whole day. This is something that SHOULD be included in the documentation for Visual Studio Code for MacOS for debugging.

**Comment by eriolchan** [comment] 2019-07-25 09:11
**Access is denied when debugging C# module on macOS**

**Description:**
Error message of "Access is denied" occurs when debugging C# module on macOS.

**Cause:**
The root cause is that certificate of _edge-device-ca.cert.pem_ is not added to keychain.

**Workaround:**
For local debug,
1. Add _edge-device-ca.cert.pem_ to your keychain manually, and remove the env "_EdgeModuleCACertificateFile_".

For remote debug (using iotedgehubdev),
1. Start IoT Edge Simulator for Single Module.
2. Edit _.vscode/launch.json_, remove the env "_EdgeModuleCACertificateFile_" in your CSharp module project launch mode debug setting.
3. Add _edge-device-ca.cert.pem_ to your keychain.
4. Start debugging the CSharp module in launch mode.

**Comment by kiranpradeep** [comment] 2019-09-03 08:30
Adding third party issue for transparency https://github.com/Azure/azure-iot-sdk-csharp/issues/574

**Comment by rlimberger** [comment] 2019-10-25 00:52
Im running into this too. Where do I get `edge-device-ca.cert.pem` from?

**Comment by rlimberger** [comment] 2019-10-25 01:31
I followed these steps:

1. add /var/lib/iotedgehubdev/certs/edge-device-ca/cert/edge-device-ca.cert.pem to system keychain and set "always trust" manually
2. removed EdgeModuleCACertificateFile from launch.json

This changed the exception from:
`System.Security.Cryptography.CryptographicException : Access is denied.`
To:
`System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.`

Still not able to debug C# on local simulator using VS Code on Mac.

**Comment by thomashoef** [comment] 2020-08-31 08:56
> I followed these steps:
> 
> 1. add /var/lib/iotedgehubdev/certs/edge-device-ca/cert/edge-device-ca.cert.pem to system keychain and set "always trust" manually
> 2. removed EdgeModuleCACertificateFile from launch.json
> 
> This changed the exception from:
> `System.Security.Cryptography.CryptographicException : Access is denied.`
> To:
> `System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.`
> 
> Still not able to debug C# on local simulator using VS Code on Mac.

@rlimberger Hi René, I am facing the same issue. Did you manage to resolve the second error? Thanks!

**Comment by konichi3** [comment] 2021-01-09 00:54
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:54 UTC
Labels: external dependency
