### ISSUE TITLE
SSL verification issue when starting edge Hub Dev

### ISSUE THREAD

**Issue by kbeaugrand** [Azure/iotedgehubdev#268] opened 2020-03-31 14:05 UTC
Hi, 
I'm facing issues while starting the edge hub dev behind my corporate proxy. 
The proxy is intercepting the HTTP streams and re-cipher the stream with its own certificate authority which is not globally trusted.
Here is the error I'm facing : 
```
ERROR: HTTPSConnectionPool(host='*******.azure-devices.net', port=443): Max retries exceeded with url: /devices/devkbe/modules/$edgeHub?api-version=2018-06-30 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

When testing the SSL certificate I can confirm the issue: 

```
openssl s_client -connect *******.azure-devices.net:443
CONNECTED(00000164)
depth=0 CN = *******.azure-devices.net
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *******.azure-devices.net
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = *******.azure-devices.net
   i:C = CA, ST = Ontario, L = Ottawa, O = Corpo Group, OU = MSS, CN = *****-Web-Gateway2, emailAddress = soc.mss@corpo.com
---
Server certificate
```

Is there a way to specify the trusted root certificates for iot edge hub dev ? 

I'm running on Windows 10.

Regards,

**Comment by SLdragon** [comment] 2020-04-02 01:39
Hi, @kbeaugrand , edge hub dev do not have settings to setup the trusted root certificates, I think you should trust your cert in system level.  You can follow this link to trust it: https://docs.microsoft.com/en-us/skype-sdk/sdn/articles/installing-the-trusted-root-certificate

**Comment by kbeaugrand** [comment] 2020-04-03 17:48
Hi, 

The certificate used by the proxy is well-known by the system. 
BTW, messages shown by the openssl client is present only because the certiticate is not present in the openssl default store. 

Do we have to install the certificate in the python's store (for example, by using certify, ...) ? 

Regards,

**Comment by SLdragon** [comment] 2020-04-07 04:27
Hi, kbeaugrand,
The problem is that Python request library do not use system certificates store, so you would meet this error.

Our simulator now do not have ways to setup python request certificate store now, and I think you can try certify which is supported by request library.

Here are some discusses about this, maybe you can refer:
https://stackoverflow.com/questions/10667960/python-requests-throwing-sslerror
https://stackoverflow.com/questions/50422136/python-requests-with-wincertstore

**Comment by konichi3** [comment] 2021-01-09 00:57
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:57 UTC
Labels: external dependency
