### ISSUE TITLE
Environement Variables are not working

### ISSUE THREAD

**Issue by Fredborg** [Azure/iotedgehubdev#265] opened 2020-02-10 09:33 UTC
Hi,

I believe Environment Variables doesnt work at all in the EdgeHub Dev simulator.

I tried a simple test. I created a new empty module called EnvVariableModule. In deployment.debug.template.json i configured the module with 1 Environment Variable called ENV_VAR like so:

`"EnvVariableModule": { "version": "1.0.0", "type": "docker", "status": "running", "restartPolicy": "always", "settings": { "image": "${MODULEDIR<../EnvVariableModule>.debug}", "createOptions": { "Env": [ "ENV_VAR=MyCoolVariable" ] } } } }`

In program.cs I added the following line of code to retrieve the value of ENV_VAR like so:

string environmentVar = Environment.GetEnvironmentVariable("ENV_VAR");

When starting up environmentVar = null

Why is this not working?

**Comment by SLdragon** [comment] 2020-02-11 03:03
Hi, @Fredborg, I think your env settings is not correct, please follow the example below to setup environment variables:

```
"Module_Name": {
    "version": "1.0",
    "type": "docker",
    "status": "running",
    "restartPolicy": "always",
    "settings": {
        "image": "${MODULEDIR<../EnvVariableModule>.debug}",
        "createOptions": {}
    },
    "env": {
        "ENV_VAR": {
            "value": "MyCoolVariable"
        }
    }
}
```

**Comment by SLdragon** [comment] 2020-02-13 03:19
Hi, @Fredborg, I also tested your settings, and it works, here is the sample config:

sample module:
```
"SimulatedTemperatureSensor": {
    "version": "1.0",
    "type": "docker",
    "status": "running",
    "restartPolicy": "always",
    "settings": {
        "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
        "createOptions": {
            "Env": [
                "ENV_VAR=MyCoolVariable"
            ]
        }
    }
}
```

Then in the generated docker-compose.yml file it could contain ENV_VAR environment variable:

```
  SimulatedTemperatureSensor:
    container_name: SimulatedTemperatureSensor
    depends_on:
    - edgeHubDev
    environment:
    - ENV_VAR=MyCoolVariable
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
    - EdgeHubConnectionString=***
    image: mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
    labels:
      iotedgehubdev: ''
    networks:
      azure-iot-edge-dev: null
    restart: always
    volumes:
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
```

So I think your setting is OK, after starting the module, please check the docker-compose.yml whether contain this env on your machine (you can find the yml file here: C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml)

**Comment by SLdragon** [comment] 2020-02-20 02:51
Hi, @Fredborg , have you solve your problem? And I will close this issue, if you still have problem, feel free to contact us

**Comment by mikanyg** [comment] 2020-03-30 09:54
@SLdragon Which version of iotedgedev did you test on? I am seeing same issues as @Fredborg.

I cannot get the "Env" to work in createOptions when debugging in iotedgedev.

**Comment by mikanyg** [comment] 2020-03-30 12:56
@SLdragon I have tried experimenting some more on using environment variables with C# custom iot edge modules, and I will try to highlight my findings.

My setup
OS: Windows 10 (1909)
Docker Desktop (2.2.0.4)
Docker Engine (19.03.8)
Visual Studio 2019 Pro (16.5.1) with Azure Iot Edge Tools for VS2019 Extension (v1.5.0)
iotedgehubdev: 0.13.0

Sample solution:
1. Created new C# Azure Iot Edge (Linux amd64) solution 
2. Create a C# custom Iot Edge module _IotEdgeModule1_

Added 
```c#
Console.WriteLine($"Environment variable value: {Environment.GetEnvironmentVariable("MYVAR")}");
```
to `Init()` method of `Programs.cs` in  _IotEdgeModule1_.
```c#
static async Task Init()
{
   // ... (vs generated code)
   Console.WriteLine($"Environment variable value: {Environment.GetEnvironmentVariable("MYVAR")}");
}
```
Updated `deployment.debug.template.json` with various options:

Finding 1: Update module twin properties for environment variable for __IotEdgeModule1__
Outcome: __It works__, the env var can be read from IotEdgeModule1 when running in edgeHubDev.
Example:
```json
        "modules": {
          "IotEdgeModule1": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULEDIR<../IotEdgeModule1>.debug}",
              "createOptions": {}
            },
            "env": {
              "MYVAR": {
                "value": "Hello from MYVAR"
              }
            }
          }
        }
```

Finding 2: Update createOptions with environment variables for __IotEdgeModule1__
Outcome: __It does NOT work__, and `C:\ProgramData\iotedgehubdev\data\datadocker-compose.yml` is NOT updated with env var MYVAR.
Example:
```json
"modules": {
          "IotEdgeModule1": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULEDIR<../IotEdgeModule1>.debug}",
              "createOptions": {
                "Env": [
                  "MYVAR=HelloFromMYVAR"
                ]
              }
            }
          }
        }
```

Finding 3: Update createOptions with environment variables for __edgeHub (system module)__
Outcome: __It does NOT work__, but `C:\ProgramData\iotedgehubdev\data\datadocker-compose.yml` IS updated with env var MYVAR.
Example:
```json
"edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
                 ...
                },
                "Env": [
                  "MYVAR=HelloFromMYVAR"
                ]
              }
            }
          }
```

Finding 4: Update iot edge settings in Visual Studio options
Outcome: __It does NOT work__, even though build output log shows that the environment variables are found and used.
Example: 
![image](https://user-images.githubusercontent.com/3300695/77913379-701e9480-7294-11ea-85c0-7d20814dcb19.png)

Finding 5: Update module twin properties for environment variable with value from .env file (in Iot Edge project folder)
Outcome: __It does NOT work__, the actual value from .env file is not picked up (tried $MYCUSTOMVAR and ${MYCUSTOMVAR} syntax.
Example: 
```json
        "modules": {
          "IotEdgeModule1": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULEDIR<../IotEdgeModule1>.debug}",
              "createOptions": {}
            },
            "env": {
              "MYVAR": {
                "value": "${MYCUSTOMVAR}"
              }
            }
          }
        }
```

So getting environment variables to work in custom C# during local development with iotedgehubdev only works for Finding 1. 
The [first attempt your confirmed working](https://github.com/Azure/iotedgehubdev/issues/265#issuecomment-585530043) is for a docker image that is downloaded and hosted outside of edgehubdev container, which works with createOptions, but the problem is with environment variable in custom modules during development.

I would expect that some of the scenarios I described would be applicable during development, especially setting environment variables through the Visual Studio settings as well as replacing values from .env file. Otherwise you are left with hardcoding values and commiting them to source control.

I hope this issue will be reopened and some of the scenarios fixed.

**Comment by mikanyg** [comment] 2020-04-20 20:36
@SLdragon Any chanche this issue could be reopened, please see all my [findings](https://github.com/Azure/iotedgehubdev/issues/265#issuecomment-605982472) with environment variables not working in VS2019. Some of these scenarios I would expect to work when developing with VS2019.

**Comment by cjrada** [comment] 2020-12-18 11:10
Did this issue ever get resolved?  I've tested as per @mikanyg with identical results.  I would expect these solutions to work.  I don't see any workaround or alternate solution listed.  Does this issue need to be reopened?

**Comment by marianan** [comment] 2020-12-18 14:41
@mikanyg and @cjrada - thank you for reporting this issue. We have added it to our backlog for investigations and will follow up here when we have details to share.

**Comment by konichi3** [comment] 2021-01-09 00:56
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:56 UTC

**Comment by marianan** [comment] 2021-11-17 23:30
@mikanyg @Fredborg i just tried again using the latest iotedgehubdev 0.14.10 and still cannot reproduce the issue you are observing. If the C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml does not update after rebuilding the deployment.debug.template.json and launching the solution in the simulator, i am guessing that the simulator is still running while you are rebuilding. I recommend to make sure to run the "**Azure IoT Edge: Stop IoT Edge SImulator**" command before rebuilding and starting the simulator to make sure that the simulator gets a chance to pick up the updated docker-compose file.

I wonder if something is missing in my repro steps. Could you take a look at the screenshot below and let me know if I need any other changes?
![image](https://user-images.githubusercontent.com/10135329/142298479-2b266a67-edcc-48dc-a5fa-3906c0e412dd.png)

**Comment by sandervanteinde** [comment] 2021-11-26 07:09
@marianan I am encountering the same issue, however I notice you are running it through VSCode and using docker if I'm not mistaken by the logging that you posted?

I am running it through Visual Studio 2019 using the following extension: https://marketplace.visualstudio.com/items?itemName=vsc-iot.vs16iotedgetools.

In that situation I am encountering exactly the same issue as @Fredborg.
@mikanyg is describing some pretty clear reproduction steps, however he described that Finding 1 is working for him. That is however, not working for me.

If you want, I can provide you more information, just let me know what you need.

**Comment by sandervanteinde** [comment] 2021-12-03 13:31
The solution of @mikanyg worked. we unfortunately nested the object 1 level deeper and than it doesn't work.

**Comment by mhshami01** [comment] 2022-03-01 22:06
The API **Environment.GetEnvironmentVariable("MYVAR")** will look for the requested variable from the environment where the application is running. When running individual modules inside the debugger, the API will look in the environment of the system where the debugger/IDE is installed and running. Currently, the only supported way to set that value for the given environment is to set it at the system level. One way maybe to 'set MYVAR=value' from the VS2019/VS2022 development command before launching devenv.

Alternatively, you can use the simulator to debug your module(s). The simulator uses docker containers for launching each module in the solution. To set environment variables in this scenario, you can add the following entry in the 'createOptions' of each module:
"Env": [ "MYVAR=Hello MyVar", "MYVAR2=Hello MyVar2" ]
