### ISSUE TITLE
[query] Invoking direct methods with curl

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedgehubdev#263] opened 2020-01-13 13:27 UTC
While debugging a single module natively, is it possible to invoke a direct method with a curl command?

**Comment by SLdragon** [comment] 2020-01-16 05:19
Hi, @kiranpradeep , you can use the curl to call direct methods, the docs can be found here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#example


First, you can use Azure IoT Tools to generate **IoT Hub** SAS Token:
![image](https://user-images.githubusercontent.com/5545529/72495762-8ce52780-3862-11ea-85af-d233b7344251.png)

Then use the curl command below to Invoke direct methods:

```
curl -X POST \
  https://xxx.azure-devices.net/twins/device4/methods?api-version=2018-06-30 \
  -H 'Authorization: SharedAccessSignature sr=xxx.azure-devices.net&sig=xxx&skn=iothubowner&se=xxx' \
  -H 'Content-Type: application/json' \
  -d '{
    "methodName": "reboot",
    "responseTimeoutInSeconds": 200,
    "payload": {
        "input1": "someInput",
        "input2": "anotherInput"
    }
}'
```

**Comment by kiranpradeep** [comment] 2020-01-16 07:17
I am with limited access to internet (only outbund is via a corporate ssl decrypting http proxy) and so had raised #209. Then it was suggested [[comment](https://github.com/Azure/iotedgehubdev/issues/209#issuecomment-568758393)] that edgeHubDev needs to connect just once. Now for this a persistent conntetion will be required.

I can use the curl request to `localhost` for sending messages on input endpoint. Shouldn't the simulator provide a similar mechanism with curl targeted at `localhost`?

**Comment by SLdragon** [comment] 2020-01-20 02:23
Hi, @kiranpradeep, according to the [docs](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods), direct method should called from IoT Hub side, so if you do not have internet access, then the direct method should not work.

Recently our simulator do not have mechanism to simulate direct method, and I will disccuss with team members about this.

**Comment by kiranpradeep** [comment] 2020-01-20 02:38
@SLdragon That is not true. We have an implementation in which uses direct methods between modules. The iotedge repository even have an [example](https://github.com/Azure/iotedge/blob/1.0.8.4/edge-modules/DirectMethodSender/src/Program.cs#L70) for this. This approach was put forward by MS engineers itself for a usecase.

**Comment by SLdragon** [comment] 2020-01-20 03:27
Oh, thanks for your information.
When you're using single module debug, we created a helper container named "azureiotedge-testing-utility" which provide http endpoint to help user to send debug messages, the code can be found here: https://github.com/Azure/iot-edge-testing-utility, I think in the future release, we could add another endpoint point which help user to call direct method. I will keep this issue open, and will let you know the progress, thanks!

**Comment by konichi3** [comment] 2021-01-09 00:56
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:56 UTC
Labels: feature request
