### ISSUE TITLE
[ubuntu 18.04] install iotedgehubdev must use sudo

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#149] opened 2019-01-08 02:43 UTC
steps:
1.  pip install --upgrade iotedgehubdev 
2.  iotedgehubdev --version
command not found
3. pip uninstall iotedgehubdev
4. sudo pip install --upgrade iotedgehubdev 
5. iotedgehubdev --version
found version 0.6.0

**Comment by adashen** [comment] 2019-01-08 02:52
Currently we ask user install root on linux. Please refer to the https://github.com/Azure/iotedgehubdev#installing

By default python user path is not exposed in environment. So close the issue now since it is as designed.

**Closed by adashen** 2019-01-08 02:52 UTC

**Comment by cicorias** [comment] 2019-03-07 17:05
this should be re-opened. there really isn't a reason why any pip/python package can't run non-sudo and also be used in a python virtual env.

**Comment by adashen** [comment] 2019-03-08 01:21
@cicorias, actually, you could install iotedgehubdev without sudo, but needs make sure the user python script path is exposed. So the tool could be called in any terminal.

**Comment by kiranpradeep** [comment] 2019-09-02 12:05
@adashen Even if install as user (--user), and expose script path, the command (_iotedgehubdev setup -c "xxxxx"_) program attempts to create directories in /var/lib (on Ubuntu 18.04 and macOS 10.13.4) which is limited to root access.

**Comment by cicorias** [comment] 2019-09-02 15:45
can you try running the pip install `sudo env "PATH=$PATH" <command>` --- this is how I've worked around the limitation of iotedgedev tools and hard requirement of root. I agree this is not normal and should still be addressed.

**Comment by kiranpradeep** [comment] 2019-09-03 03:34
@cicorias Sorry. I couldn't understand the suggested command fully. The aim was to install and use _iotedgehubdev_ with out using _sudo_.

**Comment by XavierGeerinck** [comment] 2021-05-07 11:38
> env "PATH=$PATH"

Ah this did it! Commands i ran:

```bash
sudo env "PATH=$PATH" pip install iotedgehubdev --upgrade
sudo env "PATH=$PATH" iotedgehubdev setupc -C "<DEVICE_CONN_STRING>" -i "<IOT_HUB_CONN_STR>"
```

Would love to see the install guidelines updated if deemed a correct solution :) too much time wasted settings this up honestly.

**Comment by kiran-pradeep-palakkappilil** [comment] 2022-01-27 09:37
@marianan 

> The simulator tool is by design a system tool and as such requires elevated privileges

We cannot see any technical reason why this tool requires elevated privileges. If such a reason exists, could that be documented?

**Comment by cicorias** [comment] 2022-01-27 11:37
@marianan running as user is about developer experience and eliminating speed bumps to using the tool. As for sudo, it's just really bad practice to require it as it's essentially a user tool and nothing to do with the "system". You've limited usage by enforcing sudo elevation and I'm sure if the time were committed this could run sans sudo.

**Comment by marianan** [comment] 2022-03-28 16:42
The changes to run iotedgehubdev as user are ready. Please try the latest version 0.14.14

**Comment by XavierGeerinck** [comment] 2022-03-28 17:12
Awesome! Thanks a lot on this, will try it out somewhere this week
