### ISSUE TITLE
Environment Variables not working, EventGrid on Edge cannot run

### ISSUE THREAD

**Issue by Fredborg** [Azure/iotedgehubdev#264] opened 2020-01-24 11:36 UTC
Hi,

It seems that Environment variables are not working in IoTEdgehub Dev.

Several Microsoft released modules, depends on Environment variables being set when starting up, but they are not when running using IoTEdgeHubDev - for instance EventGrid on Edge, depends on the following variables being set at startup:

IOTEDGE_MODULEID
IOTEDGE_DEVICEID
IOTEDGE_IOTHUBHOSTNAME
IOTEDGE_MODULEGENERATIONID
IOTEDGE_GATEWAYHOSTNAME
IOTEDGE_APIVERSION
IOTEDGE_WORKLOADURI

I have tried to set these variables in the deployment.debug.template.json code like so:
`"EventGridModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azure-event-grid/iotedge:latest",
              "createOptions": {
                "Env": [
                  "inbound:clientAuth:clientCert:enabled=false",
                  "inbound:serverAuth:tlsPolicy=enabled",
                  "outbound:webhook:httpsOnly=false",
                  "IOTEDGE_MODULEID=EventGrid"
                ],
                "HostConfig": {
                  "Binds": [
                    "d:\\iiotedge\\eventgrid:/app/metadataDb"
                  ],
                  "PortBindings": {
                    "4438/tcp": [
                      {
                        "HostPort": "4438"
                      }
                    ]
                  }
                }
              }
            }
          }`
   
But setting the variable IOTEDGE_MODULEID doesnt work. 
I also tried setting the variable in IotEdge extension in Visual Studio 2019 under Tools -> Azure Iot Edge tools -> Iot Edge Tools Settings, in the Other Environment Variables. No matter where i set the Variables, it doesnt seem to set them in the IoT EdgeHub Dev Simulator.

**I'm using the following versions:**
Visual Studio 2019 Pro - 16.4.3
IotEdgeHub Dev - 0.13.0
Docker - 19.03.5

And i'm deploying my Edge solution to Linux Amd architecture in Debug mode.

Regards
Anders

**Comment by adashen** [comment] 2020-02-03 02:27
Hi @Fredborg, currently EventGrid module is not supported to run on simulator. And the required set of  environments are only provided in real edge runtime. We will mark the issue as feature request and keep you updated when we have it enabled.

**Comment by Fredborg** [comment] 2020-02-03 12:38
Hi,

Thanks for the response - its very much appreciated :)

I believe the issue here, is not related to the EventGrid Module, but to the fact that Environment Variables doesnt work at all in the EdgeHub Dev simulator.

I tried a simple test. I created a new empty module called EnvVariableModule. In deployment.debug.template.json i confgiured the module with 1 Environment Variable called ENV_VAR like so:

`"EnvVariableModule": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULEDIR<../EnvVariableModule>.debug}",
              "createOptions": {
                "Env": [
                  "ENV_VAR=MyCoolVariable"
                  ]
                }
              }
            }
          }`

In program.cs I added the following line of code to retrieve the value of ENV_VAR like so:

string environmentVar = Environment.GetEnvironmentVariable("ENV_VAR");

When starting up environmentVar = null

Why is this not working?

**Comment by SLdragon** [comment] 2020-02-20 02:55
Hi, @Fredborg , for you questions about Environment Variables, please refer this issue: https://github.com/Azure/iotedgehubdev/issues/265

**Comment by shizn** [comment] 2020-07-09 04:59
Similar to https://github.com/Azure/event-grid-iot-edge/issues/2

**Comment by konichi3** [comment] 2021-01-09 00:56
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:56 UTC
Labels: feature request
