### ISSUE TITLE
Update Azure DevOps Windows agent version to 1809

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgehubdev#179] opened 2019-03-01 07:33 UTC
...and reenable test cases for Windows such as https://github.com/Azure/iotedgehubdev/blob/3ec241a7ff862da6e23cb017ae64d25da7f6eb68/tests/test_cli.py#L458

**Comment by SLdragon** [comment] 2019-12-13 03:52
There are no Azure hosted 1809 agent now, so keep this issue open util Azure DevOps provide 1809 image

**Comment by konichi3** [comment] 2021-01-09 00:55
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:55 UTC
Labels: external dependency
