### ISSUE TITLE
Expose Workload Uri and same Api as in edgelet

### ISSUE THREAD

**Issue by mma-mm** [Azure/iotedgehubdev#188] opened 2019-04-09 08:20 UTC
Hi,

i'd like to be able to debug my Edge-Module that uses IModuleDiscovery from the IIoTComponents.
This does not work.
According to @marcschier in [link](https://github.com/Azure/azure-iiot-common/issues/6) , the required api and information is available in edgelet, but not in iotedgehubdev.
In Edgelet, the workload uri is available. Also the api differs from the iotedgehubdev.
Please adapt the api of the iotedgehubdev to the api of the edgelet.

Thanks & Best regards
Matthias Mucha

**Comment by SLdragon** [comment] 2019-04-12 05:09
Hi, @mma-mm, thanks for your feedback!
iotedgehubdev is used to provide a light weight dev environment for users to debug edge module locally.
If we want to expose the workload url, it need to simulate Edgelet service, which is not easy, so we don't have the workload uri support now.

We will investigate this case and leave the issue open, if we have some progresses about this api, we will let you know.

**Comment by konichi3** [comment] 2021-01-09 00:55
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:55 UTC
Labels: feature request
