### ISSUE TITLE
Add remote debug support

### ISSUE THREAD

**Issue by lanatmwan** [Azure/iotedgehubdev#191] opened 2019-06-05 18:49 UTC
As far as I can tell, VS 2019 IoT Edge module projects don't work with remote debugging because iotedgehubdev doesn't. Remote debugging is necessary when developing on a Windows machine with an Insider build installed because Docker refuses to install. I have docker running on a remote linux machine that should work but I have no discernible options to do so in the UI.

**Comment by adashen** [comment] 2019-06-06 01:07
@lanatmwan Thanks for reporting the issue. It seems the issue is related to the vs-iot-edge extension 2019. So I have opened an issue there. https://github.com/microsoft/vs-azure-iot-edge-docs/issues/2
Please track the issue in that repo.

If there is no more comments, let's move the discussion there and I will close it in this repo to avoid confusing.

**Comment by lanatmwan** [comment] 2019-06-06 17:54
That looks like a documentation repo, not the actual extension?

**Comment by adashen** [comment] 2019-06-10 01:35
@lanatmwan Yes, Visual Studio Edge extension is not open-sourced. So https://github.com/microsoft/vs-azure-iot-edge-docs/issues is the place for issues.

**Comment by SLdragon** [comment] 2019-06-10 04:56
Hi, @lanatmwan , 
Remote debug support in Visual Studio is not straightforward, here is a blog shows how to debug remote linux module container using Visual Studio 2017.

https://devblogs.microsoft.com/iotdev/debug-iot-edge-c-or-csharp-linux-module-container-with-visual-studio-azure-iot-edge-tools/

**Comment by SLdragon** [comment] 2019-07-01 07:09
Close due to no activity, if you have any other questions, feel free to create another issue

**Closed by SLdragon** 2019-07-01 07:09 UTC
Labels: external dependency
